service: serverless-tcc

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 128



functions:
  getService:
    handler: handlers/service-handler.getService
    events:
      - http:
          path: service/{id}
          method: GET
          cors: true
  getAllServices:
    handler: handlers/service-handler.getAllServices
    events:
      - http:
          path: service
          method: GET
          cors: true
  insertService: 
    handler: handlers/service-handler.insertService
    events:
      - http:
          path: service
          method: POST
          cors: true
  getSchedule:
    handler: handlers/schedule-handler.get
    events:
      - http:
          path: schedule/{id}
          method: GET
          cors: true
  getAllSchedules:
    handler: handlers/schedule-handler.getAll
    events:
      - http:
          path: schedule
          method: GET
          cors: true
  insertSchedule: 
    handler: handlers/schedule-handler.insert
    events:
      - http:
          path: schedule
          method: POST
          cors: true
  getRequest:
    handler: handlers/request-handler.get
    events:
      - http:
          path: request/{id}
          method: GET
          cors: true
  getAllRequests:
    handler: handlers/request-handler.getAll
    events:
      - http:
          path: request
          method: GET
          cors: true
  insertRequest: 
    handler: handlers/request-handler.insert
    events:
      - http:
          path: request
          method: POST
          cors: true
  confirmRequest: 
    handler: handlers/request-handler.confirm
    events:
      - http:
          path: request/{id}/confirm
          method: PUT
          cors: true
  cancelRequest: 
    handler: handlers/request-handler.cancel
    events:
      - http:
          path: request/{id}/cancel
          method: PUT
          cors: true